male_gender: true
female_gender: false
products_per_page: 9
avatar_default: "default_avatar.png"
avatar_medium: 160
resize_avatar: 500
time_format: "%d%m%Y"
type_xls: "text/xls; charset=utf-8; header=present"
product_filters_rating: {highest_rate: "highest_rate"}
product_filters: {price_decrease: "price_decrease", price_increase: "price_increase" , get_all: "get_all"}
